server:
  port: 8090

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
security:
  oauth2:
    client:
      scope: password
      client-id: locadora
      client-secret: locadora